[2024-11-13T20:17:28.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T20:17:28.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:17:15.647839+00:00 [queued]>
[2024-11-13T20:17:28.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:17:15.647839+00:00 [queued]>
[2024-11-13T20:17:28.350+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T20:17:28.357+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-13 20:17:15.647839+00:00
[2024-11-13T20:17:28.362+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-13T20:17:15.647839+00:00', '--job-id', '8394', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpx07k_m_1']
[2024-11-13T20:17:28.364+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=726) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-13T20:17:28.364+0000] {standard_task_runner.py:91} INFO - Job 8394: Subtask dbt_test
[2024-11-13T20:17:28.364+0000] {standard_task_runner.py:63} INFO - Started process 727 to run task
[2024-11-13T20:17:28.399+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:17:15.647839+00:00 [running]> on host 4a1c99736074
[2024-11-13T20:17:28.465+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T20:17:15.647839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T20:17:15.647839+00:00'
[2024-11-13T20:17:28.465+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T20:17:28.473+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T20:17:28.474+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-13T20:17:28.480+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T20:17:29.725+0000] {subprocess.py:93} INFO - [0m20:17:29  Running with dbt=1.8.7
[2024-11-13T20:17:30.289+0000] {subprocess.py:93} INFO - [0m20:17:30  Registered adapter: snowflake=1.8.4
[2024-11-13T20:17:30.531+0000] {subprocess.py:93} INFO - [0m20:17:30  Found 6 models, 1 snapshot, 2 data tests, 2 sources, 459 macros
[2024-11-13T20:17:30.533+0000] {subprocess.py:93} INFO - [0m20:17:30
[2024-11-13T20:17:31.969+0000] {subprocess.py:93} INFO - [0m20:17:31  Concurrency: 1 threads (target='dev')
[2024-11-13T20:17:31.974+0000] {subprocess.py:93} INFO - [0m20:17:31
[2024-11-13T20:17:31.990+0000] {subprocess.py:93} INFO - [0m20:17:31  1 of 2 START test not_null_stock_indicators_symbol_date_id ..................... [RUN]
[2024-11-13T20:17:32.867+0000] {subprocess.py:93} INFO - [0m20:17:32  1 of 2 PASS not_null_stock_indicators_symbol_date_id ........................... [[32mPASS[0m in 0.87s]
[2024-11-13T20:17:32.873+0000] {subprocess.py:93} INFO - [0m20:17:32  2 of 2 START test unique_stock_indicators_symbol_date_id ....................... [RUN]
[2024-11-13T20:17:33.694+0000] {subprocess.py:93} INFO - [0m20:17:33  2 of 2 FAIL 180 unique_stock_indicators_symbol_date_id ......................... [[31mFAIL 180[0m in 0.82s]
[2024-11-13T20:17:33.702+0000] {subprocess.py:93} INFO - [0m20:17:33
[2024-11-13T20:17:33.703+0000] {subprocess.py:93} INFO - [0m20:17:33  Finished running 2 data tests in 0 hours 0 minutes and 3.17 seconds (3.17s).
[2024-11-13T20:17:33.760+0000] {subprocess.py:93} INFO - [0m20:17:33
[2024-11-13T20:17:33.762+0000] {subprocess.py:93} INFO - [0m20:17:33  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-13T20:17:33.762+0000] {subprocess.py:93} INFO - [0m20:17:33
[2024-11-13T20:17:33.763+0000] {subprocess.py:93} INFO - [0m20:17:33  [31mFailure in test unique_stock_indicators_symbol_date_id (models/schema.yml)[0m
[2024-11-13T20:17:33.764+0000] {subprocess.py:93} INFO - [0m20:17:33    Got 180 results, configured to fail if != 0
[2024-11-13T20:17:33.764+0000] {subprocess.py:93} INFO - [0m20:17:33
[2024-11-13T20:17:33.765+0000] {subprocess.py:93} INFO - [0m20:17:33    compiled code at target/compiled/lab2/models/schema.yml/unique_stock_indicators_symbol_date_id.sql
[2024-11-13T20:17:33.765+0000] {subprocess.py:93} INFO - [0m20:17:33
[2024-11-13T20:17:33.766+0000] {subprocess.py:93} INFO - [0m20:17:33  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[2024-11-13T20:17:34.531+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-13T20:17:34.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T20:17:34.555+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-13T20:17:34.570+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-13T20:17:15.647839+00:00, execution_date=20241113T201715, start_date=20241113T201728, end_date=20241113T201734
[2024-11-13T20:17:34.591+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8394 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 727)
[2024-11-13T20:17:34.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-13T20:17:34.625+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T20:17:34.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
