[2024-11-13T20:05:44.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T20:05:44.840+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:03:06.694624+00:00 [queued]>
[2024-11-13T20:05:44.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:03:06.694624+00:00 [queued]>
[2024-11-13T20:05:44.851+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T20:05:44.873+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-13 20:03:06.694624+00:00
[2024-11-13T20:05:44.880+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-13T20:03:06.694624+00:00', '--job-id', '8390', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp0q7b26y0']
[2024-11-13T20:05:44.883+0000] {standard_task_runner.py:91} INFO - Job 8390: Subtask dbt_test
[2024-11-13T20:05:44.883+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-13T20:05:44.885+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-11-13T20:05:44.935+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T20:03:06.694624+00:00 [running]> on host 4a1c99736074
[2024-11-13T20:05:45.059+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T20:03:06.694624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T20:03:06.694624+00:00'
[2024-11-13T20:05:45.060+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T20:05:45.074+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T20:05:45.077+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-13T20:05:45.109+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T20:05:47.141+0000] {subprocess.py:93} INFO - [0m20:05:47  Running with dbt=1.8.7
[2024-11-13T20:05:48.209+0000] {subprocess.py:93} INFO - [0m20:05:48  Registered adapter: snowflake=1.8.4
[2024-11-13T20:05:48.657+0000] {subprocess.py:93} INFO - [0m20:05:48  Found 6 models, 1 snapshot, 2 data tests, 2 sources, 459 macros
[2024-11-13T20:05:48.665+0000] {subprocess.py:93} INFO - [0m20:05:48
[2024-11-13T20:05:50.166+0000] {subprocess.py:93} INFO - [0m20:05:50  Concurrency: 1 threads (target='dev')
[2024-11-13T20:05:50.180+0000] {subprocess.py:93} INFO - [0m20:05:50
[2024-11-13T20:05:50.200+0000] {subprocess.py:93} INFO - [0m20:05:50  1 of 2 START test not_null_stock_indicators_symbol_date_id ..................... [RUN]
[2024-11-13T20:05:51.049+0000] {subprocess.py:93} INFO - [0m20:05:51  1 of 2 PASS not_null_stock_indicators_symbol_date_id ........................... [[32mPASS[0m in 0.84s]
[2024-11-13T20:05:51.054+0000] {subprocess.py:93} INFO - [0m20:05:51  2 of 2 START test unique_stock_indicators_symbol_date_id ....................... [RUN]
[2024-11-13T20:05:51.748+0000] {subprocess.py:93} INFO - [0m20:05:51  2 of 2 FAIL 1 unique_stock_indicators_symbol_date_id ........................... [[31mFAIL 1[0m in 0.69s]
[2024-11-13T20:05:51.758+0000] {subprocess.py:93} INFO - [0m20:05:51
[2024-11-13T20:05:51.759+0000] {subprocess.py:93} INFO - [0m20:05:51  Finished running 2 data tests in 0 hours 0 minutes and 3.08 seconds (3.08s).
[2024-11-13T20:05:51.815+0000] {subprocess.py:93} INFO - [0m20:05:51
[2024-11-13T20:05:51.816+0000] {subprocess.py:93} INFO - [0m20:05:51  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-13T20:05:51.816+0000] {subprocess.py:93} INFO - [0m20:05:51
[2024-11-13T20:05:51.817+0000] {subprocess.py:93} INFO - [0m20:05:51  [31mFailure in test unique_stock_indicators_symbol_date_id (models/schema.yml)[0m
[2024-11-13T20:05:51.818+0000] {subprocess.py:93} INFO - [0m20:05:51    Got 1 result, configured to fail if != 0
[2024-11-13T20:05:51.818+0000] {subprocess.py:93} INFO - [0m20:05:51
[2024-11-13T20:05:51.819+0000] {subprocess.py:93} INFO - [0m20:05:51    compiled code at target/compiled/lab2/models/schema.yml/unique_stock_indicators_symbol_date_id.sql
[2024-11-13T20:05:51.819+0000] {subprocess.py:93} INFO - [0m20:05:51
[2024-11-13T20:05:51.819+0000] {subprocess.py:93} INFO - [0m20:05:51  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[2024-11-13T20:05:53.154+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-13T20:05:53.169+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T20:05:53.243+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-13T20:05:53.277+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-13T20:03:06.694624+00:00, execution_date=20241113T200306, start_date=20241113T200544, end_date=20241113T200553
[2024-11-13T20:05:53.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8390 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 289)
[2024-11-13T20:05:53.363+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-13T20:05:53.412+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
